execute pathogen#infect()

set ttimeoutlen=10

set relativenumber
set number
set scrolloff=9999
set tabstop=4
set shiftwidth=4
set showcmd
set cursorline
set smartindent
set wildmenu
set incsearch
set lazyredraw
set nocompatible
set noshowmode
set noswapfile
set shortmess+=A " ignore swap warnings
set ignorecase
set smartcase " when searching
filetype on

if &term =~ '^screen'
	set ttymouse=xterm2
endif

au BufRead,BufNewFile *.fig setfiletype pug

set nofoldenable
set foldmethod=indent
au BufWinLeave ?* mkview 1
au BufWinEnter ?* silent loadview 1

let g:mapleader = ","

nnoremap <silent> <Leader>e :NERDTree<CR>
nnoremap <silent> <Leader>m :set mouse=a<CR>
nnoremap <silent> <Leader>n :set mouse=<CR>
vnoremap gs :'<,'>sort<CR>

let g:airline#extensions#tabline#enabled = 1
let g:airline_section_b = '%{getcwd()}'

set laststatus=2

if ! has('gui_running')
	set ttimeoutlen=10
	augroup FastEscape
		autocmd!
		au InsertEnter * set timeoutlen=0
		au InsertLeave * set timeoutlen=1000
	augroup END
endif

let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
set t_Co=256

if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif

let g:airline_symbols.space = "\ua0"

let delimitMate_expand_cr = 1

let g:neocomplete#enable_at_startup = 1

let g:SuperTabDefaultCompletionType = "<c-n>"

let NERDTreeShowHidden=1

let g:closetag_filenames = "*.html,*.tag"

colorscheme monokai

function! TrailingWhitespace ()
	highlight clear MatchParen
	highlight MatchParen cterm=bold,underline term=bold,underline

	highlight ExtraWhitespace cterm=underline,bold term=bold,underline ctermfg=red
	match ExtraWhitespace /\s\+$/
endfunction

syntax on
au BufWinEnter * :call TrailingWhitespace()
au VimEnter * silent AirlineToggleWhitespace

call TrailingWhitespace()

au BufEnter * set colorcolumn=80
set colorcolumn=80
