return {
	{ '1', 'Dash'},
	{ '2', 'MacDown' },
	{ '3', 'Trello' },
	{ '4', 'iTunes' },
	{ '5', 'Skim' },
	{ 'a', 'Slack' },
	{ 'b', 'Basecamp 3' },
	{ 'c', 'Caprine' },
	{ 'd', '2Do' },
	{ 'f', 'FileZilla' },
	{ 'g', 'Google Chrome' },
	{ 'h', 'Insomnia' },
	{ 'i', 'Discord' },
	{ 'k', 'Activity Monitor' },
	{ 'l', 'SnippetsLab' },
	{ 'm', 'Mail' },
	{ 'p', 'Postico' },
	{ 'q', 'Finder' },
	{ 'r', 'Microsoft Remote Desktop' },
	{ 's', 'Safari' },
	{ 't', 'kitty' },
	{ 'v', 'MacVim' },
	{ 'x', 'Calendar' }
}
